require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/gempackagetask'

require 'lib/lolspeak'

$KCODE = "UTF-8"

task :default => [:test_units]

desc "Run basic tests"
Rake::TestTask.new("test_units") do |t|
  t.pattern = 'test/*_test.rb'
  t.verbose = false
  t.warning = true
end

PKG_VERSION = LOLspeak::VERSION
PKG_FILES = FileList[
  '[A-Z]*', 
  'bin/**/*',
  'lib/**/*',
  'test/**/*',
]

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "LOLspeak translator"
  s.name = "lolspeak"
  s.version = PKG_VERSION
  s.requirements << 'none'
  s.require_path = 'lib'
  s.files = PKG_FILES
  s.bindir = 'bin'
  s.executables = ['lolspeak']
  s.description = <<-EOF
  Traslates English text into LOLspeak.
  EOF
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
