require 'rake'
require 'rake/testtask'

$KCODE = "UTF-8"

task :default => [:test_units]

desc "Run basic tests"
Rake::TestTask.new("test_units") { |t|
  t.pattern = 'test/*_test.rb'
  t.verbose = false
  t.warning = true
}
